
services:
  openhands-htur:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:htur
    container_name: openhands-htur-${DATE:-}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.30-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace/htur}
      - WORKSPACE_BASE=${WORKSPACE_BASE:-$PWD/workspace/htur}
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE:-$PWD/workspace/htur}:/opt/workspace_base
    pull_policy: missing
    stdin_open: true
    tty: true

  openhands-ugaan:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:ugaan
    container_name: openhands-ugaan-${DATE:-}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.28-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace/ugaan}
      - WORKSPACE_BASE=${WORKSPACE_BASE:-$PWD/workspace/ugaan}
    ports:
      - "3002:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE:-$PWD/workspace/ugaan}:/opt/workspace_base
    pull_policy: missing
    stdin_open: true
    tty: true

  openhands-imama:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:imama
    container_name: openhands-imama-${DATE:-}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.28-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace/imama}
      - WORKSPACE_BASE=${WORKSPACE_BASE:-$PWD/workspace/imama}
    ports:
      - "3003:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE:-$PWD/workspace/imama}:/opt/workspace_base
    pull_policy: missing
    stdin_open: true
    tty: true
 